apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-laravel
spec:
  selector:
    matchLabels:
      app: laravel
  replicas: 12
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: hello-laravel
          image: apolo96/hello-laravel:v2
          ports:
            - containerPort: 80