apiVersion: v1
kind: Service
metadata:
  name: hello-laravel
spec:
  type: LoadBalancer
  selector:   
      app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http